

export const NAVBUTTON_INCREMENT_SIZE = 'NAVBUTTON_INCREMETN_SIZE';
export type NAVBUTTON_INCREMENT_SIZE = typeof NAVBUTTON_INCREMENT_SIZE;

export const NAVBUTTON_DECREMENT_SIZE = 'NAVBUTTON_DECREMETN_SIZE';
export type NAVBUTTON_DECREMENT_SIZE = typeof NAVBUTTON_DECREMENT_SIZE;
